language: java
jdk:
  - openjdk10

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache

sudo: required
dist: trusty
#services:
#  - docker

notifications:
  email:
    - kulinskyvs@gmail.com
  on_success: always
  on_failure: always

branches:
  only:
    - master

env:
  global:
    # encrypted GRGIT_USER
    - secure: 81sTnatE6xHk8cqC8PJIrEeHcKvgawLS5ZNOVMvVvjGLpMnomA1AsobTFozu7MeaDuTkyITSxEoaHbl9V929rdtS2lTvtBuu0bDCQAmI8e+q9C99zs17nUJ+OrVDmmb9npfdy0zbMou9sVYO4cDiMVxADchn/JDKgVmgInW9e9xH1fLO232bSjePHYeCau+TNf2bKMQbVCyXdXTw7LD3JPVFgl33EUrCc5WwGnjlEk5clkA6cvs4iq2ryfl78x+SwN+qgPTyeO8FdWpEQit6g2wM/uuaeH52on/UH/seUKQiudHUmPOPUb1ARZe2Lp8Pg3F1tIS1NhEL5D46YrDUd67Hoi5LrQ/UOSTBh8nzZRMYs/dF1kfZkAyJI90ZjslCSvTmpLBTfdEr9z2u0AXNMDLiwplbgdVpIcQT1L774geGaSIlYZxeM8vqL/0L8C6VmTitLPm/LYP7vzpWLuZPSvMQ15dmGAv5iaolgjoL0K11oLOyB5x8Ql2IEelEaYOm+YC9Y+0rYYKT/aFUhnsmE8nNrBFdMGSslGCBfFBflG5deJZXn2np5GHHS1sHiJMgUnHc5CdPrJKD8u1Xh8FWq2Fdt4gcJMsSZhnqbEhyX/a3htc+Tlu/b7SP/cBCMGUag0nhbOAamQ+fvnVc7m/oe/V/s6c8gcJFeWv5ZmsJmY4=
    # encrypted GRGIT_PASS
    - secure: 3+CN45fDSVtVQPC3SuSrqGhyx8HFYMJVpVkqcw+2dvZgqSAO/A5MTdHUX3bfBfau3rginDA+6JcPpOc4evaJof4OL49rZAUCBXlyREQQ5Rar8XT7bjUuslRTxqks7qm8iYJ8Zs4fNaPJwKFnU92JTI0e8Xddq2TJtawGN11GiqbdF9ALzHTrDygDiaY1loitq3AMCUtSJdHvnhWVsT0iqlHnY5ls9pdrBsUhchGMM7EbToVivSPLKYTmPiEoPDaOZwTnejNMvJs6ubPWqW8ezMGiB+1DaZPneqLzjK4qNdNzZPZOZADjs+WcmsJu9r1Vb5X7Bs4TVsdBAjH6WDxBZkRw18WXgLdyXMcxJgIra9CmZETyVAjXXmGuaNAn1dAhUjtOuSBBMgcqE3OsiRapMEeL3CdvtnJxBEDqEItiLuagYn33bQRgyqpa7XcVClnkUSSbAzUwrprrb15vptDLaEZQKE0VG0xjxXZkpR+TzYTDEOyExpp1IKVGgv+eSh0oUBMQL8zBJsEL5ZgEFJQ7+uh4pFD2Zu5oKIbd/1Suoh8MdITb2iYGxz00HIpb+65tYl7/adrGqUYiMJKecSfMmqO+V5K15JoW994EiFkw4/wOSa+bGz9JH0RoS4B+LIbHkLNu9mnnASI3hFSac4HR1yEuW01e2yx9jS5pl1rGzgs=

addons:
  sonarcloud:
    organization: "kulinskyvs-github" # the key of the org from sonar cloud
    token:
      # encrypted value of your token from sonar cloud
      secure: "dy5cymzotVkmHi1gFf5eLfYjTK81MAcy4VL51M+fiu+L+uiVY1K4qq+qzwnmqfuuCg2IY/YK5Qyn2OClBZvHxzmLK/XabgfGZf1sLpu6NcskPOPpPiSmTm8A22H1HrKCN7vf8LxzxJ1k0jRi5pFarNYsQ7zwEl0wwg8qfvZOOZeYbXxkbhSs2E43wUYr/TRVy8tCMWXf4wquGROc26wkCvHnlEeM+qwYKAxaEeCktaFz8z/3jL/3GEXUXn7NI/DVMmi5XhNP+9MmguvcA/SOs1KmCjXO9Wy1d1j4l/zItiPpzdTvCI4C8qR1fDIZ5GdC2oeVz8RjRaDkqoEam9Y1FVDcs4HMG4DTITixwpytUB9pcXMbK9o5VIJ9HkPuclipqHmLyRgLMuSLE9AHuhtCGzDMrt5yJ/wTAisNI4Zn7fXQhwkk7toDLVlaagNcJNWd1lUP5lAqxm2sE47xpuAG0nDgqPSFUSS11XFwlNivaCWHAoExKpKoGvvAGrKsU2QPVFCqVgVqwOWaq0/sbmGgF15RmHC0kjV4TJQqUypD3QsvdIU9+4aXAhCF84ddG3grKEK/dxTaUhJeSEJ46IG1OWOJqii19eCb2776dls+IoDY3uvqwnacEHmZIlcNL9qODUKejGJbDkXCsKxI+2FmlDZe1ORcBVY31QPaarpgMbo="

before_install:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#  - gem install travis -v 1.8.5 --no-rdoc --no-ri
#  - sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
#  - sudo chmod +x /usr/local/bin/ecs-cli
#  - export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
#  - export CONTAINER_IP=54.215.193.139
#  - export PLATFORM_TEST_NAME="chapter10-platform-tests"

script:
  - ./gradlew clean build jacocoTestReport
  - sonar-scanner
  - ./gradlew tagRevision
#  - sh travis_scripts/tag_build.sh
#  - sh travis_scripts/build_services.sh
#  - sh travis_scripts/deploy_to_docker_hub.sh
#  - sh travis_scripts/deploy_to_amazon_ecs.sh
# sh travis_scripts/trigger_platform_tests.sh

after_success:
  - ./gradlew coveralls


